begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is((select mode from app_private.announcement_executor),'LEGACY','installation preserves legacy');
select ok((select relrowsecurity from pg_class where oid='app_private.announcement_executor'::regclass),'executor is deny-by-default RLS');
select is((select count(*) from app_private.worker_claim_announcement_push(false)),0::bigint,'worker cannot claim before handoff');
select ok(not has_table_privilege('asisteam_jobs','public.push_tokens','SELECT'),'jobs has no token table access');
select ok(not has_table_privilege('asisteam_jobs','app_private.announcement_push_deliveries','SELECT,UPDATE'),'jobs cannot read or forge queue');
select ok(not has_column_privilege('asisteam_api','public.push_tokens','token','SELECT'),'API never reads token column');
select ok(has_column_privilege('asisteam_api','public.push_tokens','id','SELECT'),'API may project device existence under RLS');
select ok(has_function_privilege('asisteam_api','public.publish_group_announcement(uuid,text,text,uuid)','EXECUTE'),'API uses canonical write');
select ok(not has_function_privilege('asisteam_api','app_private.worker_claim_announcement_push(boolean)','EXECUTE'),'API cannot claim deliveries');
select ok(not has_function_privilege('service_role','app_private.worker_claim_announcement_push(boolean)','EXECUTE'),'legacy credential cannot use worker');
select ok(not has_function_privilege('asisteam_jobs','public.claim_announcement_push(boolean)','EXECUTE'),'worker cannot use legacy claim');
select ok(not has_function_privilege('asisteam_jobs','app_private.canonical_claim_announcement_push(boolean)','EXECUTE'),'worker cannot bypass executor mode');
select ok(not has_function_privilege('service_role','app_private.canonical_complete_announcement_push(uuid,uuid,text,text)','EXECUTE'),'legacy cannot bypass receipt fence');
select ok(not has_function_privilege('asisteam_jobs','app_private.announcement_handoff(text,boolean)','EXECUTE'),'jobs cannot activate handoff');
select ok(not has_function_privilege('asisteam_api','app_private.announcement_handoff(text,boolean)','EXECUTE'),'API cannot activate handoff');
select ok(not has_function_privilege('authenticated','app_private.announcement_handoff(text,boolean)','EXECUTE'),'user cannot activate handoff');
select ok((select bool_and(prosecdef and proconfig @> array['search_path=""']) from pg_proc where oid in ('app_private.worker_claim_announcement_push(boolean)'::regprocedure,'app_private.worker_complete_announcement_push(uuid,uuid,text,text)'::regprocedure,'app_private.announcement_handoff(text,boolean)'::regprocedure)),'privileged functions have fixed search_path');
select app_private.announcement_handoff('DRAINING');
select is((select count(*) from cron.job where jobname='send-announcement-push'),0::bigint,'only legacy push cron is removed');
select throws_ok($$select public.claim_announcement_push(false)$$,'55000','Ejecutor anterior deshabilitado','legacy claims fenced while draining');
select lives_ok($$select app_private.dispatch_announcement_push()$$,'dispatcher does nothing after drain');
select throws_ok($$select app_private.announcement_handoff('WORKER',true)$$,'55000','Debe completarse el drenaje del ejecutor anterior','minimum drain time enforced');
update app_private.announcement_executor set draining_since=now()-interval '4 minutes';
select throws_ok($$select app_private.announcement_handoff('WORKER')$$,'55000','Debe completarse el drenaje del ejecutor anterior','time is not operator attestation');
select app_private.announcement_handoff('WORKER',true);
select is((select mode from app_private.announcement_executor),'WORKER','operator activation recorded');
select ok((select activated_at is not null and draining_since is not null from app_private.announcement_executor),'handoff keeps timestamps for evidence');
select throws_ok($$select public.claim_announcement_push(false)$$,'55000','Ejecutor anterior deshabilitado','legacy claims remain disabled');
select throws_ok($$select public.complete_announcement_push(gen_random_uuid(),gen_random_uuid(),'accepted','ticket')$$,'55000','Ejecutor anterior deshabilitado','legacy ACK cannot write after activation');
select throws_ok($$select app_private.worker_complete_announcement_push(gen_random_uuid(),gen_random_uuid(),'accepted','ticket')$$,'55000','Reserva vencida o cancelada','unleased worker ACK fenced');
select throws_ok($$select app_private.announcement_handoff('LEGACY',true)$$,'55000','Transición de ejecutor inválida','cannot rollback by flag alone');
select ok(not (app_private.announcement_worker_metrics()::text ~ 'token|user_id|title|body'),'metrics contain only aggregates');
select * from finish();
rollback;
