begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select ok(not rolsuper and not rolbypassrls and not rolcreaterole and not rolcreatedb and not rolreplication, 'API no tiene capacidades privilegiadas') from pg_roles where rolname='asisteam_api';
select ok(not exists(select 1 from pg_class where relnamespace in ('public'::regnamespace,'app_private'::regnamespace) and pg_has_role('asisteam_api',relowner,'USAGE')), 'API no es propietario');
select ok(not has_schema_privilege('asisteam_api','public','CREATE') and not has_schema_privilege('asisteam_api','app_private','CREATE'), 'rutas definer no escribibles');
select ok(not pg_has_role('asisteam_api','service_role','MEMBER'), 'API separado de service_role');
select ok(not has_table_privilege('asisteam_api','auth.sessions','SELECT'), 'API no puede leer sesiones/refresh');
select ok(not has_table_privilege('asisteam_api','auth.users','SELECT'), 'API no puede leer credenciales');
select ok(not has_function_privilege('authenticated','app_private.api_session_user_id(uuid)','EXECUTE'), 'PostgREST autenticado no invoca adaptador');
select ok(not has_function_privilege('anon','app_private.api_session_user_id(uuid)','EXECUTE'), 'anon no invoca adaptador');
select ok(not has_function_privilege('asisteam_jobs','app_private.api_session_user_id(uuid)','EXECUTE') and not has_function_privilege('asisteam_webhook','app_private.api_session_user_id(uuid)','EXECUTE'), 'roles privados separados');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.prosecdef and n.nspname in ('public','app_private') and has_function_privilege('asisteam_api',p.oid,'EXECUTE') and not exists(select 1 from unnest(p.proconfig) setting where setting like 'search_path=%')), 'cada definer accesible fija search_path');
set local role asisteam_api;
select set_config('request.jwt.claim.sub','',true),set_config('request.jwt.claims','{}',true);
select is(auth.uid(),null::uuid,'contexto ausente no tiene identidad Auth');
select is(public.auth_user_id(),null::uuid,'contexto ausente no tiene perfil');
select is(app_private.api_session_user_id(gen_random_uuid()),null::uuid,'sesión sin contexto falla cerrada');
select is((select count(*) from public.v_my_groups),0::bigint,'sin contexto ningún grupo');
select ok(not pg_has_role('asisteam_api','authenticated','SET'),'API no tiene SET de authenticated');
select ok(not pg_has_role('asisteam_api','service_role','SET'),'API no tiene SET de service_role');
reset role;
select * from finish();
rollback;
