begin;
select plan(20);
select ok(not has_table_privilege('asisteam_auth','app_private.auth_credentials','SELECT'),'Auth no lee tablas directamente');
select ok(not has_table_privilege('asisteam_api','app_private.auth_credentials','SELECT'),'API de dominio no lee contraseñas');
select ok(not has_table_privilege('authenticated','app_private.auth_credentials','SELECT'),'Cliente no lee contraseñas');
select ok(not has_function_privilege('authenticated','app_private.auth_operation(text,jsonb)','EXECUTE'),'Cliente no invoca identidad');
select ok(not has_function_privilege('asisteam_api','app_private.auth_operation(text,jsonb)','EXECUTE'),'Rol API no muta credenciales');
select ok(has_function_privilege('asisteam_auth','app_private.auth_operation(text,jsonb)','EXECUTE'),'Solo Auth ejecuta casos de uso');
select ok(not has_function_privilege('asisteam_auth','app_private.accept_invitation(text,uuid,jsonb)','EXECUTE'),'Auth no elude registro transaccional');
select ok(not has_schema_privilege('asisteam_auth','app_private','CREATE'),'Auth no crea funciones');
select ok(not has_schema_privilege('asisteam_auth','public','CREATE'),'Auth no crea recursos públicos');
select ok(not (select rolsuper or rolbypassrls or rolcreaterole or rolcreatedb from pg_roles where rolname='asisteam_auth'),'Auth sin superusuario/BYPASSRLS');
select ok(not exists(select 1 from pg_auth_members m join pg_roles r on r.oid=m.member where r.rolname='asisteam_auth'),'Auth no hereda roles');
select ok((select bool_and(relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='app_private' and c.relname in ('auth_subjects','auth_credentials','auth_families','auth_refresh','auth_recovery','auth_attempts')),'Tablas Auth RLS deny by default');
select is((select count(*)::int from public.users u join app_private.auth_credentials c on c.subject_id=u.auth_user_id where u.account_status='MANAGED'),0,'MANAGED sin credenciales');
select ok((select pg_get_functiondef('app_private.accept_invitation(text,uuid,jsonb)'::regprocedure) like '%select email into v_auth_email from app_private.auth_subjects where id = p_auth_user_id;%'),'Aceptación usa sujeto estable');
select ok((select pg_get_functiondef('app_private.accept_invitation(text,uuid,jsonb)'::regprocedure) like '%ACCOUNT_ACTIVATION_MINOR%'),'Aceptación conserva consentimiento separado');
select ok((select pg_get_functiondef('app_private.accept_invitation(text,uuid,jsonb)'::regprocedure) like '%app_private.group_membership_limit%'),'Aceptación conserva cupos canónicos');
select ok((select pg_get_functiondef('app_private.accept_invitation(text,uuid,jsonb)'::regprocedure) like '%CB-06%'),'Claim conserva historia canónica');
select is(app_private.native_session_user_id(gen_random_uuid()),null::uuid,'Sin contexto no hay sesión native');
select ok(not has_function_privilege('authenticated','app_private.native_session_user_id(uuid)','EXECUTE'),'Cliente no usa adaptador interno');
select ok(has_function_privilege('asisteam_api','app_private.native_session_user_id(uuid)','EXECUTE'),'API usa adaptador privado');
select * from finish();
rollback;
