// Generated by packages/db/scripts/types.mjs from PostgreSQL 17 catalogs.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type PersistenceSchema = {
  "public": {
    Tables: {
      "account_consents": {
        Row: {
          "id": string;
          "user_id": string;
          "terms_version": string;
          "granted_at": string;
          "channel": string;
        };
        Insert: {
          "id"?: string;
          "user_id": string;
          "terms_version": string;
          "granted_at"?: string;
          "channel": string;
        };
        Update: {
          "id"?: string;
          "user_id"?: string;
          "terms_version"?: string;
          "granted_at"?: string;
          "channel"?: string;
        };
        Relationships: [];
      };
      "activities": {
        Row: {
          "id": string;
          "group_id": string;
          "activity_type_id": string;
          "title": string;
          "description": string | null;
          "location": string | null;
          "starts_at": string;
          "ends_at": string;
          "created_by": string;
          "created_at": string;
          "updated_at": string;
          "recurrence_rule": Json | null;
          "recurrence_source_id": string | null;
        };
        Insert: {
          "id"?: string;
          "group_id": string;
          "activity_type_id": string;
          "title": string;
          "description"?: string | null;
          "location"?: string | null;
          "starts_at": string;
          "ends_at": string;
          "created_by": string;
          "created_at"?: string;
          "updated_at"?: string;
          "recurrence_rule"?: Json | null;
          "recurrence_source_id"?: string | null;
        };
        Update: {
          "id"?: string;
          "group_id"?: string;
          "activity_type_id"?: string;
          "title"?: string;
          "description"?: string | null;
          "location"?: string | null;
          "starts_at"?: string;
          "ends_at"?: string;
          "created_by"?: string;
          "created_at"?: string;
          "updated_at"?: string;
          "recurrence_rule"?: Json | null;
          "recurrence_source_id"?: string | null;
        };
        Relationships: [];
      };
      "activity_types": {
        Row: {
          "id": string;
          "group_id": string | null;
          "name": string;
          "color": string;
          "is_active": boolean;
        };
        Insert: {
          "id"?: string;
          "group_id"?: string | null;
          "name": string;
          "color"?: string;
          "is_active"?: boolean;
        };
        Update: {
          "id"?: string;
          "group_id"?: string | null;
          "name"?: string;
          "color"?: string;
          "is_active"?: boolean;
        };
        Relationships: [];
      };
      "announcement_push_preferences": {
        Row: {
          "user_id": string;
          "enabled": boolean;
        };
        Insert: {
          "user_id": string;
          "enabled"?: boolean;
        };
        Update: {
          "user_id"?: string;
          "enabled"?: boolean;
        };
        Relationships: [];
      };
      "attendance_records": {
        Row: {
          "id": string;
          "activity_id": string;
          "membership_id": string;
          "status": string;
          "note": string | null;
          "recorded_by": string;
          "recorded_at": string;
        };
        Insert: {
          "id"?: string;
          "activity_id": string;
          "membership_id": string;
          "status": string;
          "note"?: string | null;
          "recorded_by": string;
          "recorded_at"?: string;
        };
        Update: {
          "id"?: string;
          "activity_id"?: string;
          "membership_id"?: string;
          "status"?: string;
          "note"?: string | null;
          "recorded_by"?: string;
          "recorded_at"?: string;
        };
        Relationships: [];
      };
      "billing_plans": {
        Row: {
          "code": string;
          "name": string;
          "amount_clp": number;
          "athlete_limit": number;
          "currency": string;
        };
        Insert: {
          "code": string;
          "name": string;
          "amount_clp": number;
          "athlete_limit": number;
          "currency"?: string;
        };
        Update: {
          "code"?: string;
          "name"?: string;
          "amount_clp"?: number;
          "athlete_limit"?: number;
          "currency"?: string;
        };
        Relationships: [];
      };
      "birthdate_change_approvals": {
        Row: {
          "request_id": string;
          "group_id": string;
          "approved_by": string;
          "approved_at": string;
        };
        Insert: {
          "request_id": string;
          "group_id": string;
          "approved_by": string;
          "approved_at"?: string;
        };
        Update: {
          "request_id"?: string;
          "group_id"?: string;
          "approved_by"?: string;
          "approved_at"?: string;
        };
        Relationships: [];
      };
      "birthdate_change_requests": {
        Row: {
          "id": string;
          "user_id": string;
          "old_birthdate": string;
          "requested_birthdate": string;
          "status": string;
          "created_at": string;
          "resolved_at": string | null;
        };
        Insert: {
          "id"?: string;
          "user_id": string;
          "old_birthdate": string;
          "requested_birthdate": string;
          "status"?: string;
          "created_at"?: string;
          "resolved_at"?: string | null;
        };
        Update: {
          "id"?: string;
          "user_id"?: string;
          "old_birthdate"?: string;
          "requested_birthdate"?: string;
          "status"?: string;
          "created_at"?: string;
          "resolved_at"?: string | null;
        };
        Relationships: [];
      };
      "consents": {
        Row: {
          "id": string;
          "guardianship_id": string;
          "consent_type": string;
          "terms_version": string;
          "granted_at": string;
          "revoked_at": string | null;
          "channel": string | null;
          "allows_avatar": boolean;
        };
        Insert: {
          "id"?: string;
          "guardianship_id": string;
          "consent_type": string;
          "terms_version": string;
          "granted_at"?: string;
          "revoked_at"?: string | null;
          "channel"?: string | null;
          "allows_avatar"?: boolean;
        };
        Update: {
          "id"?: string;
          "guardianship_id"?: string;
          "consent_type"?: string;
          "terms_version"?: string;
          "granted_at"?: string;
          "revoked_at"?: string | null;
          "channel"?: string | null;
          "allows_avatar"?: boolean;
        };
        Relationships: [];
      };
      "group_announcements": {
        Row: {
          "id": string;
          "group_id": string;
          "title": string;
          "body": string;
          "created_by": string;
          "created_at": string;
          "updated_at": string;
          "deleted_at": string | null;
        };
        Insert: {
          "id"?: string;
          "group_id": string;
          "title": string;
          "body": string;
          "created_by": string;
          "created_at"?: string;
          "updated_at"?: string;
          "deleted_at"?: string | null;
        };
        Update: {
          "id"?: string;
          "group_id"?: string;
          "title"?: string;
          "body"?: string;
          "created_by"?: string;
          "created_at"?: string;
          "updated_at"?: string;
          "deleted_at"?: string | null;
        };
        Relationships: [];
      };
      "group_subscriptions": {
        Row: {
          "id": string;
          "group_id": string;
          "plan_code": string;
          "amount_clp": number;
          "athlete_limit": number;
          "requested_by": string;
          "status": string;
          "provider_subscription_id": string | null;
          "checkout_url": string | null;
          "creation_attempted_at": string | null;
          "provider_updated_at": string | null;
          "next_payment_at": string | null;
          "activated_at": string | null;
          "created_at": string;
          "updated_at": string;
        };
        Insert: {
          "id"?: string;
          "group_id": string;
          "plan_code": string;
          "amount_clp": number;
          "athlete_limit": number;
          "requested_by": string;
          "status"?: string;
          "provider_subscription_id"?: string | null;
          "checkout_url"?: string | null;
          "creation_attempted_at"?: string | null;
          "provider_updated_at"?: string | null;
          "next_payment_at"?: string | null;
          "activated_at"?: string | null;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Update: {
          "id"?: string;
          "group_id"?: string;
          "plan_code"?: string;
          "amount_clp"?: number;
          "athlete_limit"?: number;
          "requested_by"?: string;
          "status"?: string;
          "provider_subscription_id"?: string | null;
          "checkout_url"?: string | null;
          "creation_attempted_at"?: string | null;
          "provider_updated_at"?: string | null;
          "next_payment_at"?: string | null;
          "activated_at"?: string | null;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Relationships: [];
      };
      "groups": {
        Row: {
          "id": string;
          "name": string;
          "sport": string | null;
          "description": string | null;
          "logo_url": string | null;
          "invite_code": string;
          "settings": Json;
          "created_by": string;
          "created_at": string;
          "updated_at": string;
          "settings_updated_by": string | null;
          "settings_updated_at": string | null;
        };
        Insert: {
          "id"?: string;
          "name": string;
          "sport"?: string | null;
          "description"?: string | null;
          "logo_url"?: string | null;
          "invite_code": string;
          "settings"?: Json;
          "created_by": string;
          "created_at"?: string;
          "updated_at"?: string;
          "settings_updated_by"?: string | null;
          "settings_updated_at"?: string | null;
        };
        Update: {
          "id"?: string;
          "name"?: string;
          "sport"?: string | null;
          "description"?: string | null;
          "logo_url"?: string | null;
          "invite_code"?: string;
          "settings"?: Json;
          "created_by"?: string;
          "created_at"?: string;
          "updated_at"?: string;
          "settings_updated_by"?: string | null;
          "settings_updated_at"?: string | null;
        };
        Relationships: [];
      };
      "guardianships": {
        Row: {
          "id": string;
          "guardian_user_id": string;
          "athlete_user_id": string;
          "relationship": string;
          "status": string;
          "created_at": string;
          "deactivated_at": string | null;
        };
        Insert: {
          "id"?: string;
          "guardian_user_id": string;
          "athlete_user_id": string;
          "relationship": string;
          "status"?: string;
          "created_at"?: string;
          "deactivated_at"?: string | null;
        };
        Update: {
          "id"?: string;
          "guardian_user_id"?: string;
          "athlete_user_id"?: string;
          "relationship"?: string;
          "status"?: string;
          "created_at"?: string;
          "deactivated_at"?: string | null;
        };
        Relationships: [];
      };
      "invitations": {
        Row: {
          "id": string;
          "group_id": string;
          "email": string | null;
          "role": string;
          "token": string;
          "invited_user_id": string | null;
          "status": string;
          "expires_at": string;
          "created_by": string;
          "created_at": string;
          "accepted_at": string | null;
          "terms_version": string | null;
          "activation_membership_id": string | null;
        };
        Insert: {
          "id"?: string;
          "group_id": string;
          "email"?: string | null;
          "role": string;
          "token": string;
          "invited_user_id"?: string | null;
          "status"?: string;
          "expires_at"?: string;
          "created_by": string;
          "created_at"?: string;
          "accepted_at"?: string | null;
          "terms_version"?: string | null;
          "activation_membership_id"?: string | null;
        };
        Update: {
          "id"?: string;
          "group_id"?: string;
          "email"?: string | null;
          "role"?: string;
          "token"?: string;
          "invited_user_id"?: string | null;
          "status"?: string;
          "expires_at"?: string;
          "created_by"?: string;
          "created_at"?: string;
          "accepted_at"?: string | null;
          "terms_version"?: string | null;
          "activation_membership_id"?: string | null;
        };
        Relationships: [];
      };
      "job_runs": {
        Row: {
          "id": string;
          "job_name": string;
          "run_date": string;
          "completed_at": string;
          "affected_count": number;
        };
        Insert: {
          "id"?: string;
          "job_name": string;
          "run_date": string;
          "completed_at"?: string;
          "affected_count": number;
        };
        Update: {
          "id"?: string;
          "job_name"?: string;
          "run_date"?: string;
          "completed_at"?: string;
          "affected_count"?: number;
        };
        Relationships: [];
      };
      "memberships": {
        Row: {
          "id": string;
          "user_id": string;
          "group_id": string;
          "role": string;
          "status": string;
          "joined_at": string | null;
          "created_at": string;
          "updated_at": string;
        };
        Insert: {
          "id"?: string;
          "user_id": string;
          "group_id": string;
          "role": string;
          "status": string;
          "joined_at"?: string | null;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Update: {
          "id"?: string;
          "user_id"?: string;
          "group_id"?: string;
          "role"?: string;
          "status"?: string;
          "joined_at"?: string | null;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Relationships: [];
      };
      "push_tokens": {
        Row: {
          "id": string;
          "user_id": string;
          "platform": string;
          "token": string;
          "is_active": boolean;
          "created_at": string;
          "last_seen_at": string;
        };
        Insert: {
          "id"?: string;
          "user_id": string;
          "platform": string;
          "token": string;
          "is_active"?: boolean;
          "created_at"?: string;
          "last_seen_at"?: string;
        };
        Update: {
          "id"?: string;
          "user_id"?: string;
          "platform"?: string;
          "token"?: string;
          "is_active"?: boolean;
          "created_at"?: string;
          "last_seen_at"?: string;
        };
        Relationships: [];
      };
      "subscription_invoices": {
        Row: {
          "provider_invoice_id": string;
          "subscription_id": string;
          "due_at": string;
          "amount_clp": number;
          "status": string;
          "provider_payment_id": string | null;
          "paid_at": string | null;
          "provider_updated_at": string;
          "created_at": string;
        };
        Insert: {
          "provider_invoice_id": string;
          "subscription_id": string;
          "due_at": string;
          "amount_clp": number;
          "status": string;
          "provider_payment_id"?: string | null;
          "paid_at"?: string | null;
          "provider_updated_at": string;
          "created_at"?: string;
        };
        Update: {
          "provider_invoice_id"?: string;
          "subscription_id"?: string;
          "due_at"?: string;
          "amount_clp"?: number;
          "status"?: string;
          "provider_payment_id"?: string | null;
          "paid_at"?: string | null;
          "provider_updated_at"?: string;
          "created_at"?: string;
        };
        Relationships: [];
      };
      "users": {
        Row: {
          "id": string;
          "auth_user_id": string | null;
          "full_name": string;
          "email": string | null;
          "phone": string | null;
          "birthdate": string | null;
          "avatar_url": string | null;
          "account_status": string;
          "created_at": string;
          "updated_at": string;
        };
        Insert: {
          "id"?: string;
          "auth_user_id"?: string | null;
          "full_name": string;
          "email"?: string | null;
          "phone"?: string | null;
          "birthdate"?: string | null;
          "avatar_url"?: string | null;
          "account_status"?: string;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Update: {
          "id"?: string;
          "auth_user_id"?: string | null;
          "full_name"?: string;
          "email"?: string | null;
          "phone"?: string | null;
          "birthdate"?: string | null;
          "avatar_url"?: string | null;
          "account_status"?: string;
          "created_at"?: string;
          "updated_at"?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      "v_activity_types": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "name": string | null;
          "color": string | null;
          "is_active": boolean | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "name"?: string | null;
          "color"?: string | null;
          "is_active"?: boolean | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "name"?: string | null;
          "color"?: string | null;
          "is_active"?: boolean | null;
        };
        Relationships: [];
      };
      "v_athlete_attendance_history": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "membership_id": string | null;
          "activity_id": string | null;
          "title": string | null;
          "starts_at": string | null;
          "activity_type_id": string | null;
          "activity_type_name": string | null;
          "activity_type_color": string | null;
          "is_system_type": boolean | null;
          "status": string | null;
          "note": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_id"?: string | null;
          "title"?: string | null;
          "starts_at"?: string | null;
          "activity_type_id"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_id"?: string | null;
          "title"?: string | null;
          "starts_at"?: string | null;
          "activity_type_id"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Relationships: [];
      };
      "v_attendance_admin": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "activity_id": string | null;
          "membership_id": string | null;
          "status": string | null;
          "note": string | null;
          "recorded_by": string | null;
          "recorded_at": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
          "recorded_by"?: string | null;
          "recorded_at"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
          "recorded_by"?: string | null;
          "recorded_at"?: string | null;
        };
        Relationships: [];
      };
      "v_attendance_operator": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "activity_id": string | null;
          "membership_id": string | null;
          "status": string | null;
          "note": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Relationships: [];
      };
      "v_attendance_own": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "activity_id": string | null;
          "membership_id": string | null;
          "status": string | null;
          "note": string | null;
          "recorded_at": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
          "recorded_at"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_id"?: string | null;
          "membership_id"?: string | null;
          "status"?: string | null;
          "note"?: string | null;
          "recorded_at"?: string | null;
        };
        Relationships: [];
      };
      "v_attendance_roster": {
        Row: {
          "membership_id": string | null;
          "group_id": string | null;
          "full_name": string | null;
          "avatar_url": string | null;
        };
        Insert: {
          "membership_id"?: string | null;
          "group_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
        };
        Update: {
          "membership_id"?: string | null;
          "group_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
        };
        Relationships: [];
      };
      "v_group_activities": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "activity_type_id": string | null;
          "title": string | null;
          "description": string | null;
          "location": string | null;
          "starts_at": string | null;
          "ends_at": string | null;
          "activity_type_name": string | null;
          "activity_type_color": string | null;
          "is_system_type": boolean | null;
          "recurrence_rule": Json | null;
          "recurrence_source_id": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_type_id"?: string | null;
          "title"?: string | null;
          "description"?: string | null;
          "location"?: string | null;
          "starts_at"?: string | null;
          "ends_at"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "recurrence_rule"?: Json | null;
          "recurrence_source_id"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "activity_type_id"?: string | null;
          "title"?: string | null;
          "description"?: string | null;
          "location"?: string | null;
          "starts_at"?: string | null;
          "ends_at"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "recurrence_rule"?: Json | null;
          "recurrence_source_id"?: string | null;
        };
        Relationships: [];
      };
      "v_group_attendance_report": {
        Row: {
          "group_id": string | null;
          "membership_id": string | null;
          "activity_type_id": string | null;
          "activity_date": string | null;
          "convened": number | null;
          "present": number | null;
          "late": number | null;
          "absent": number | null;
          "excused": number | null;
          "attendance_pct": number | null;
          "late_rate": number | null;
        };
        Insert: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_type_id"?: string | null;
          "activity_date"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Update: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_type_id"?: string | null;
          "activity_date"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Relationships: [];
      };
      "v_group_detail": {
        Row: {
          "id": string | null;
          "name": string | null;
          "sport": string | null;
          "description": string | null;
          "logo_url": string | null;
          "roles": (string)[] | null;
          "invite_code": string | null;
          "settings": Json | null;
          "can_view_group_stats": boolean | null;
          "settings_updated_at": string | null;
          "settings_updated_by_name": string | null;
        };
        Insert: {
          "id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "description"?: string | null;
          "logo_url"?: string | null;
          "roles"?: (string)[] | null;
          "invite_code"?: string | null;
          "settings"?: Json | null;
          "can_view_group_stats"?: boolean | null;
          "settings_updated_at"?: string | null;
          "settings_updated_by_name"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "description"?: string | null;
          "logo_url"?: string | null;
          "roles"?: (string)[] | null;
          "invite_code"?: string | null;
          "settings"?: Json | null;
          "can_view_group_stats"?: boolean | null;
          "settings_updated_at"?: string | null;
          "settings_updated_by_name"?: string | null;
        };
        Relationships: [];
      };
      "v_group_stats_members": {
        Row: {
          "group_id": string | null;
          "membership_id": string | null;
          "full_name": string | null;
          "avatar_url": string | null;
          "convened": number | null;
          "present": number | null;
          "late": number | null;
          "absent": number | null;
          "excused": number | null;
          "attendance_pct": number | null;
          "late_rate": number | null;
        };
        Insert: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Update: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Relationships: [];
      };
      "v_my_groups": {
        Row: {
          "id": string | null;
          "name": string | null;
          "sport": string | null;
          "logo_url": string | null;
          "roles": (string)[] | null;
        };
        Insert: {
          "id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "logo_url"?: string | null;
          "roles"?: (string)[] | null;
        };
        Update: {
          "id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "logo_url"?: string | null;
          "roles"?: (string)[] | null;
        };
        Relationships: [];
      };
      "v_my_ward_groups": {
        Row: {
          "athlete_user_id": string | null;
          "group_id": string | null;
          "name": string | null;
          "sport": string | null;
          "membership_status": string | null;
        };
        Insert: {
          "athlete_user_id"?: string | null;
          "group_id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "membership_status"?: string | null;
        };
        Update: {
          "athlete_user_id"?: string | null;
          "group_id"?: string | null;
          "name"?: string | null;
          "sport"?: string | null;
          "membership_status"?: string | null;
        };
        Relationships: [];
      };
      "v_my_wards": {
        Row: {
          "athlete_user_id": string | null;
          "full_name": string | null;
          "avatar_url": string | null;
          "age": number | null;
          "days_until_majority": number | null;
        };
        Insert: {
          "athlete_user_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
          "age"?: number | null;
          "days_until_majority"?: number | null;
        };
        Update: {
          "athlete_user_id"?: string | null;
          "full_name"?: string | null;
          "avatar_url"?: string | null;
          "age"?: number | null;
          "days_until_majority"?: number | null;
        };
        Relationships: [];
      };
      "v_ward_attendance_history": {
        Row: {
          "id": string | null;
          "group_id": string | null;
          "athlete_user_id": string | null;
          "membership_id": string | null;
          "activity_id": string | null;
          "title": string | null;
          "starts_at": string | null;
          "activity_type_id": string | null;
          "activity_type_name": string | null;
          "activity_type_color": string | null;
          "is_system_type": boolean | null;
          "status": string | null;
          "note": string | null;
        };
        Insert: {
          "id"?: string | null;
          "group_id"?: string | null;
          "athlete_user_id"?: string | null;
          "membership_id"?: string | null;
          "activity_id"?: string | null;
          "title"?: string | null;
          "starts_at"?: string | null;
          "activity_type_id"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Update: {
          "id"?: string | null;
          "group_id"?: string | null;
          "athlete_user_id"?: string | null;
          "membership_id"?: string | null;
          "activity_id"?: string | null;
          "title"?: string | null;
          "starts_at"?: string | null;
          "activity_type_id"?: string | null;
          "activity_type_name"?: string | null;
          "activity_type_color"?: string | null;
          "is_system_type"?: boolean | null;
          "status"?: string | null;
          "note"?: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      "accept_account_terms": { Args: { "p_accepted": boolean; "p_terms_version": string }; Returns: string };
      "accept_invitation": { Args: { "p_token_hash": string; "p_auth_user_id": string }; Returns: Json };
      "approve_membership": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: undefined };
      "assign_member_coach": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: string };
      "auth_user_id": { Args: {  }; Returns: string };
      "can_read_avatar": { Args: { "p_name": string }; Returns: boolean };
      "can_upload_avatar": { Args: {  }; Returns: boolean };
      "cancel_invitation_registration": { Args: { "p_nonce_hash": string }; Returns: undefined };
      "clear_attendance_record": { Args: { "p_activity_id": string; "p_membership_id": string }; Returns: undefined };
      "consent_managed_member": { Args: { "p_membership_id": string; "p_accepted": boolean }; Returns: undefined };
      "consent_membership_data": { Args: { "p_membership_id": string; "p_accepted": boolean }; Returns: string };
      "consume_invitation_attempt": { Args: { "p_key": string }; Returns: boolean };
      "create_activity": { Args: { "p_group_id": string; "p_activity_type_id": string; "p_title": string; "p_starts_at": string; "p_ends_at": string; "p_description"?: string; "p_location"?: string; "p_recurrence_rule"?: Json }; Returns: string };
      "create_group": { Args: { "p_name": string; "p_sport": string; "p_description"?: string; "p_logo_url"?: string }; Returns: string };
      "create_guardianship": { Args: { "p_group_id": string; "p_athlete_user_id": string; "p_full_name": string; "p_email": string; "p_relationship": string }; Returns: string };
      "create_managed_member": { Args: { "p_group_id": string; "p_full_name": string; "p_birthdate": string; "p_email"?: string; "p_guardian"?: Json }; Returns: Json };
      "deactivate_membership": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: undefined };
      "delete_activity": { Args: { "p_group_id": string; "p_activity_id": string; "p_scope"?: string; "p_confirm_attendance"?: boolean }; Returns: number };
      "delete_group_announcement": { Args: { "p_group_id": string; "p_announcement_id": string; "p_updated_at": string }; Returns: undefined };
      "get_group_attendance_report": { Args: { "p_group_id": string; "p_period"?: string; "p_from"?: string; "p_to"?: string; "p_activity_type_ids"?: (string)[]; "p_include_inactive"?: boolean; "p_page"?: number; "p_page_size"?: number; "p_sort"?: string }; Returns: Json };
      "get_group_billing": { Args: { "p_group_id": string; "p_page"?: number }; Returns: Json };
      "get_group_stats": { Args: { "p_group_id": string; "p_page"?: number; "p_page_size"?: number }; Returns: Json };
      "get_my_attendance_history": { Args: { "p_group_id": string; "p_period"?: string; "p_from"?: string; "p_to"?: string; "p_activity_type_ids"?: (string)[]; "p_page"?: number; "p_page_size"?: number }; Returns: Json };
      "get_qr_checkin_settings": { Args: { "p_group_id": string }; Returns: Json };
      "get_ward_attendance_history": { Args: { "p_group_id": string; "p_athlete_user_id": string; "p_period"?: string; "p_from"?: string; "p_to"?: string; "p_activity_type_ids"?: (string)[]; "p_page"?: number; "p_page_size"?: number }; Returns: Json };
      "has_account_consent": { Args: {  }; Returns: boolean };
      "invitation_context": { Args: { "p_token_hash": string }; Returns: Json };
      "invitation_registration_result": { Args: { "p_token_hash": string; "p_auth_user_id": string }; Returns: Json };
      "is_group_admin": { Args: { "p_group_id": string }; Returns: boolean };
      "is_guardian_of": { Args: { "p_athlete_user_id": string }; Returns: boolean };
      "is_member": { Args: { "p_group_id": string }; Returns: boolean };
      "issue_activity_checkin_qr": { Args: { "p_activity_id": string }; Returns: Json };
      "issue_invitation": { Args: { "p_auth_user_id": string; "p_group_id": string; "p_token_hash": string; "p_email"?: string; "p_role"?: string; "p_invitation_id"?: string }; Returns: Json };
      "issue_managed_activation": { Args: { "p_auth_user_id": string; "p_group_id": string; "p_membership_id": string; "p_token_hash": string }; Returns: Json };
      "join_group_as_athlete": { Args: { "p_group_id": string }; Returns: string };
      "join_group_by_code": { Args: { "p_invite_code": string }; Returns: Json };
      "list_avatar_permissions": { Args: {  }; Returns: { "guardianship_id": string; "full_name": string; "allows_avatar": boolean }[] };
      "list_birthdate_reviews": { Args: {  }; Returns: { "request_id": string; "group_id": string; "group_name": string; "full_name": string; "old_birthdate": string; "requested_birthdate": string; "approved": boolean }[] };
      "list_group_announcements": { Args: { "p_group_id": string; "p_page"?: number }; Returns: { "id": string; "group_id": string; "title": string; "body": string; "created_at": string; "updated_at": string; "total_count": number }[] };
      "list_group_members": { Args: { "p_group_id": string; "p_role"?: string; "p_status"?: string; "p_offset"?: number; "p_search"?: string }; Returns: { "membership_id": string; "full_name": string; "email": string; "phone": string; "birthdate": string; "account_status": string; "role": string; "status": string; "total_count": number; "user_id": string; "person_roles": Json; "is_last_admin": boolean }[] };
      "list_guardianship_athletes": { Args: { "p_group_id": string; "p_search"?: string; "p_offset"?: number }; Returns: { "user_id": string; "full_name": string; "total_count": number }[] };
      "list_managed_activation_requests": { Args: { "p_group_id": string; "p_offset"?: number; "p_athlete_user_id"?: string }; Returns: { "request_id": string; "membership_id": string; "full_name": string; "relationship": string; "status": string; "total_count": number }[] };
      "list_managed_member_consents": { Args: { "p_group_id": string; "p_offset"?: number }; Returns: { "membership_id": string; "full_name": string; "relationship": string; "total_count": number }[] };
      "list_membership_onboarding": { Args: { "p_group_id"?: string; "p_athlete_user_id"?: string; "p_membership_id"?: string; "p_offset"?: number; "p_as_guardian"?: boolean }; Returns: { "membership_id": string; "athlete_user_id": string; "group_id": string; "group_name": string; "full_name": string; "membership_status": string; "account_status": string; "is_minor": boolean; "guardian_linked": boolean; "guardian_ready": boolean; "requires_managed_consent": boolean; "can_consent": boolean; "relationship": string; "capacity_block": string; "total_count": number }[] };
      "list_my_wards": { Args: {  }; Returns: { "athlete_user_id": string; "full_name": string; "avatar_url": string; "age": number; "days_until_majority": number }[] };
      "list_pending_athletes": { Args: { "p_group_id": string }; Returns: { "membership_id": string; "full_name": string; "is_minor": boolean; "guardian_ready": boolean; "total_count": number }[] };
      "list_pending_memberships": { Args: { "p_group_id": string; "p_offset"?: number }; Returns: { "membership_id": string; "full_name": string; "is_minor": boolean; "guardian_linked": boolean; "guardian_ready": boolean; "requires_managed_consent": boolean; "total_count": number }[] };
      "prepare_invitation_registration": { Args: { "p_token_hash": string; "p_nonce_hash": string; "p_email": string; "p_registration": Json }; Returns: undefined };
      "publish_group_announcement": { Args: { "p_group_id": string; "p_title": string; "p_body": string; "p_request_id": string }; Returns: string };
      "reactivate_membership": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: undefined };
      "record_attendance_bulk": { Args: { "p_activity_id": string; "p_records": Json; "p_only_unmarked"?: boolean }; Returns: Json };
      "register_announcement_push_token": { Args: { "p_token": string; "p_platform": string }; Returns: string };
      "reject_pending_membership": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: undefined };
      "request_birthdate_change": { Args: { "p_birthdate": string }; Returns: string };
      "request_managed_activation": { Args: { "p_group_id": string; "p_membership_id": string }; Returns: string };
      "review_birthdate_change": { Args: { "p_request_id": string; "p_group_id": string; "p_approve": boolean }; Returns: string };
      "review_managed_activation": { Args: { "p_request_id": string; "p_accepted": boolean }; Returns: Json };
      "rotate_invite_code": { Args: { "p_group_id": string }; Returns: string };
      "self_checkin": { Args: { "p_activity_id": string; "p_token": string }; Returns: Json };
      "set_announcement_push_enabled": { Args: { "p_enabled": boolean }; Returns: undefined };
      "set_avatar_permission": { Args: { "p_guardianship_id": string; "p_allow": boolean }; Returns: undefined };
      "set_qr_checkin_settings": { Args: { "p_group_id": string; "p_settings": Json }; Returns: Json };
      "unregister_announcement_push_token": { Args: { "p_token": string }; Returns: undefined };
      "update_activity": { Args: { "p_group_id": string; "p_activity_id": string; "p_activity_type_id": string; "p_title": string; "p_starts_at": string; "p_ends_at": string; "p_description"?: string; "p_location"?: string; "p_scope"?: string }; Returns: number };
      "update_attendance_record": { Args: { "p_record_id": string; "p_changes": Json }; Returns: Json };
      "update_group_announcement": { Args: { "p_group_id": string; "p_announcement_id": string; "p_title": string; "p_body": string; "p_updated_at": string }; Returns: undefined };
      "update_group_settings": { Args: { "p_group_id": string; "p_changes": Json }; Returns: Json };
      "update_managed_member": { Args: { "p_group_id": string; "p_membership_id": string; "p_full_name": string; "p_birthdate": string; "p_email"?: string; "p_phone"?: string }; Returns: string };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
  "app_private": {
    Tables: {
      "announcement_executor": {
        Row: {
          "singleton": boolean;
          "mode": string;
          "draining_since": string | null;
          "activated_at": string | null;
        };
        Insert: {
          "singleton"?: boolean;
          "mode"?: string;
          "draining_since"?: string | null;
          "activated_at"?: string | null;
        };
        Update: {
          "singleton"?: boolean;
          "mode"?: string;
          "draining_since"?: string | null;
          "activated_at"?: string | null;
        };
        Relationships: [];
      };
      "announcement_push_deliveries": {
        Row: {
          "id": string;
          "announcement_id": string;
          "user_id": string;
          "push_token_id": string;
          "status": string;
          "attempts": number;
          "created_at": string;
          "next_attempt_at": string;
          "claimed_until": string | null;
          "claim_token": string | null;
          "ticket_id": string | null;
          "accepted_at": string | null;
          "completed_at": string | null;
          "failure_code": string | null;
        };
        Insert: {
          "id"?: string;
          "announcement_id": string;
          "user_id": string;
          "push_token_id": string;
          "status"?: string;
          "attempts"?: number;
          "created_at"?: string;
          "next_attempt_at"?: string;
          "claimed_until"?: string | null;
          "claim_token"?: string | null;
          "ticket_id"?: string | null;
          "accepted_at"?: string | null;
          "completed_at"?: string | null;
          "failure_code"?: string | null;
        };
        Update: {
          "id"?: string;
          "announcement_id"?: string;
          "user_id"?: string;
          "push_token_id"?: string;
          "status"?: string;
          "attempts"?: number;
          "created_at"?: string;
          "next_attempt_at"?: string;
          "claimed_until"?: string | null;
          "claim_token"?: string | null;
          "ticket_id"?: string | null;
          "accepted_at"?: string | null;
          "completed_at"?: string | null;
          "failure_code"?: string | null;
        };
        Relationships: [];
      };
      "auth_attempts": {
        Row: {
          "key": string;
          "count": number;
          "reset_at": string;
        };
        Insert: {
          "key": string;
          "count": number;
          "reset_at"?: string;
        };
        Update: {
          "key"?: string;
          "count"?: number;
          "reset_at"?: string;
        };
        Relationships: [];
      };
      "auth_authority": {
        Row: {
          "singleton": boolean;
          "mode": string;
          "frozen_at": string | null;
          "activated_at": string | null;
          "recovery_started_at": string | null;
        };
        Insert: {
          "singleton"?: boolean;
          "mode"?: string;
          "frozen_at"?: string | null;
          "activated_at"?: string | null;
          "recovery_started_at"?: string | null;
        };
        Update: {
          "singleton"?: boolean;
          "mode"?: string;
          "frozen_at"?: string | null;
          "activated_at"?: string | null;
          "recovery_started_at"?: string | null;
        };
        Relationships: [];
      };
      "auth_credentials": {
        Row: {
          "subject_id": string;
          "password_hash": string;
          "updated_at": string;
        };
        Insert: {
          "subject_id": string;
          "password_hash": string;
          "updated_at"?: string;
        };
        Update: {
          "subject_id"?: string;
          "password_hash"?: string;
          "updated_at"?: string;
        };
        Relationships: [];
      };
      "auth_families": {
        Row: {
          "id": string;
          "subject_id": string;
          "expires_at": string;
          "revoked_at": string | null;
          "created_at": string;
        };
        Insert: {
          "id"?: string;
          "subject_id": string;
          "expires_at"?: string;
          "revoked_at"?: string | null;
          "created_at"?: string;
        };
        Update: {
          "id"?: string;
          "subject_id"?: string;
          "expires_at"?: string;
          "revoked_at"?: string | null;
          "created_at"?: string;
        };
        Relationships: [];
      };
      "auth_import_ledger": {
        Row: {
          "subject_id": string;
          "profile_id": string;
          "source_digest": string;
          "recovery_required": boolean;
          "imported_at": string;
        };
        Insert: {
          "subject_id": string;
          "profile_id": string;
          "source_digest": string;
          "recovery_required": boolean;
          "imported_at"?: string;
        };
        Update: {
          "subject_id"?: string;
          "profile_id"?: string;
          "source_digest"?: string;
          "recovery_required"?: boolean;
          "imported_at"?: string;
        };
        Relationships: [];
      };
      "auth_oauth_transactions": {
        Row: {
          "id": string;
          "expires_at": string;
          "consumed_at": string | null;
          "link_subject_id": string | null;
          "link_session_id": string | null;
        };
        Insert: {
          "id": string;
          "expires_at"?: string;
          "consumed_at"?: string | null;
          "link_subject_id"?: string | null;
          "link_session_id"?: string | null;
        };
        Update: {
          "id"?: string;
          "expires_at"?: string;
          "consumed_at"?: string | null;
          "link_subject_id"?: string | null;
          "link_session_id"?: string | null;
        };
        Relationships: [];
      };
      "auth_recovery": {
        Row: {
          "token_hash": string;
          "subject_id": string;
          "expires_at": string;
          "consumed_at": string | null;
        };
        Insert: {
          "token_hash": string;
          "subject_id": string;
          "expires_at"?: string;
          "consumed_at"?: string | null;
        };
        Update: {
          "token_hash"?: string;
          "subject_id"?: string;
          "expires_at"?: string;
          "consumed_at"?: string | null;
        };
        Relationships: [];
      };
      "auth_refresh": {
        Row: {
          "token_hash": string;
          "family_id": string;
          "consumed_at": string | null;
        };
        Insert: {
          "token_hash": string;
          "family_id": string;
          "consumed_at"?: string | null;
        };
        Update: {
          "token_hash"?: string;
          "family_id"?: string;
          "consumed_at"?: string | null;
        };
        Relationships: [];
      };
      "auth_social_identities": {
        Row: {
          "provider": string;
          "provider_subject": string;
          "subject_id": string;
          "created_at": string;
        };
        Insert: {
          "provider": string;
          "provider_subject": string;
          "subject_id": string;
          "created_at"?: string;
        };
        Update: {
          "provider"?: string;
          "provider_subject"?: string;
          "subject_id"?: string;
          "created_at"?: string;
        };
        Relationships: [];
      };
      "auth_subjects": {
        Row: {
          "id": string;
          "email": string;
          "created_at": string;
          "disabled_until": string | null;
          "native_owned": boolean;
        };
        Insert: {
          "id": string;
          "email": string;
          "created_at"?: string;
          "disabled_until"?: string | null;
          "native_owned"?: boolean;
        };
        Update: {
          "id"?: string;
          "email"?: string;
          "created_at"?: string;
          "disabled_until"?: string | null;
          "native_owned"?: boolean;
        };
        Relationships: [];
      };
      "billing_legacy_groups": {
        Row: {
          "group_id": string;
        };
        Insert: {
          "group_id": string;
        };
        Update: {
          "group_id"?: string;
        };
        Relationships: [];
      };
      "billing_transport": {
        Row: {
          "singleton": boolean;
          "mode": string;
        };
        Insert: {
          "singleton"?: boolean;
          "mode": string;
        };
        Update: {
          "singleton"?: boolean;
          "mode"?: string;
        };
        Relationships: [];
      };
      "guardianship_majority_deliveries": {
        Row: {
          "id": string;
          "athlete_user_id": string;
          "recipient_user_id": string;
          "audience": string;
          "created_at": string;
          "sent_at": string | null;
          "claimed_at": string | null;
          "claim_token": string | null;
          "attempts": number;
          "retry_at": string;
          "first_attempt_at": string | null;
          "blocked_at": string | null;
          "payload": Json | null;
        };
        Insert: {
          "id"?: string;
          "athlete_user_id": string;
          "recipient_user_id": string;
          "audience": string;
          "created_at"?: string;
          "sent_at"?: string | null;
          "claimed_at"?: string | null;
          "claim_token"?: string | null;
          "attempts"?: number;
          "retry_at"?: string;
          "first_attempt_at"?: string | null;
          "blocked_at"?: string | null;
          "payload"?: Json | null;
        };
        Update: {
          "id"?: string;
          "athlete_user_id"?: string;
          "recipient_user_id"?: string;
          "audience"?: string;
          "created_at"?: string;
          "sent_at"?: string | null;
          "claimed_at"?: string | null;
          "claim_token"?: string | null;
          "attempts"?: number;
          "retry_at"?: string;
          "first_attempt_at"?: string | null;
          "blocked_at"?: string | null;
          "payload"?: Json | null;
        };
        Relationships: [];
      };
      "invitation_attempts": {
        Row: {
          "key": string;
          "attempts": (string)[];
          "updated_at": string;
        };
        Insert: {
          "key": string;
          "attempts": (string)[];
          "updated_at"?: string;
        };
        Update: {
          "key"?: string;
          "attempts"?: (string)[];
          "updated_at"?: string;
        };
        Relationships: [];
      };
      "invitation_registrations": {
        Row: {
          "nonce_hash": string;
          "token_hash": string;
          "email": string;
          "registration": Json;
          "expires_at": string;
        };
        Insert: {
          "nonce_hash": string;
          "token_hash": string;
          "email": string;
          "registration": Json;
          "expires_at"?: string;
        };
        Update: {
          "nonce_hash"?: string;
          "token_hash"?: string;
          "email"?: string;
          "registration"?: Json;
          "expires_at"?: string;
        };
        Relationships: [];
      };
      "invitation_send_limits": {
        Row: {
          "group_id": string;
          "day": string;
          "attempts": number;
        };
        Insert: {
          "group_id": string;
          "day": string;
          "attempts": number;
        };
        Update: {
          "group_id"?: string;
          "day"?: string;
          "attempts"?: number;
        };
        Relationships: [];
      };
      "join_code_attempts": {
        Row: {
          "user_id": string;
          "attempts": (string)[];
          "updated_at": string;
        };
        Insert: {
          "user_id": string;
          "attempts": (string)[];
          "updated_at"?: string;
        };
        Update: {
          "user_id"?: string;
          "attempts"?: (string)[];
          "updated_at"?: string;
        };
        Relationships: [];
      };
      "majority_executor": {
        Row: {
          "singleton": boolean;
          "mode": string;
          "draining_since": string | null;
          "email_next_at": string | null;
        };
        Insert: {
          "singleton"?: boolean;
          "mode"?: string;
          "draining_since"?: string | null;
          "email_next_at"?: string | null;
        };
        Update: {
          "singleton"?: boolean;
          "mode"?: string;
          "draining_since"?: string | null;
          "email_next_at"?: string | null;
        };
        Relationships: [];
      };
      "majority_tasks": {
        Row: {
          "run_date": string;
          "completed_at": string | null;
          "lease_until": string | null;
          "lease_token": string | null;
          "attempts": number;
        };
        Insert: {
          "run_date": string;
          "completed_at"?: string | null;
          "lease_until"?: string | null;
          "lease_token"?: string | null;
          "attempts"?: number;
        };
        Update: {
          "run_date"?: string;
          "completed_at"?: string | null;
          "lease_until"?: string | null;
          "lease_token"?: string | null;
          "attempts"?: number;
        };
        Relationships: [];
      };
      "managed_activation_requests": {
        Row: {
          "id": string;
          "membership_id": string;
          "requested_by": string;
          "email": string;
          "status": string;
          "consent_id": string | null;
          "requested_at": string;
          "resolved_at": string | null;
        };
        Insert: {
          "id"?: string;
          "membership_id": string;
          "requested_by": string;
          "email": string;
          "status"?: string;
          "consent_id"?: string | null;
          "requested_at"?: string;
          "resolved_at"?: string | null;
        };
        Update: {
          "id"?: string;
          "membership_id"?: string;
          "requested_by"?: string;
          "email"?: string;
          "status"?: string;
          "consent_id"?: string | null;
          "requested_at"?: string;
          "resolved_at"?: string | null;
        };
        Relationships: [];
      };
      "managed_member_enrollments": {
        Row: {
          "membership_id": string;
          "guardianship_id": string;
          "declared_by": string;
          "declared_at": string;
          "activated_at": string | null;
        };
        Insert: {
          "membership_id": string;
          "guardianship_id": string;
          "declared_by": string;
          "declared_at"?: string;
          "activated_at"?: string | null;
        };
        Update: {
          "membership_id"?: string;
          "guardianship_id"?: string;
          "declared_by"?: string;
          "declared_at"?: string;
          "activated_at"?: string | null;
        };
        Relationships: [];
      };
      "qr_checkin_keys": {
        Row: {
          "activity_id": string;
          "secret": string;
        };
        Insert: {
          "activity_id": string;
          "secret"?: string;
        };
        Update: {
          "activity_id"?: string;
          "secret"?: string;
        };
        Relationships: [];
      };
      "qr_checkin_settings": {
        Row: {
          "group_id": string;
          "opens_before_minutes": number;
          "closes_after_minutes": number;
          "late_after_minutes": number;
        };
        Insert: {
          "group_id": string;
          "opens_before_minutes"?: number;
          "closes_after_minutes"?: number;
          "late_after_minutes"?: number;
        };
        Update: {
          "group_id"?: string;
          "opens_before_minutes"?: number;
          "closes_after_minutes"?: number;
          "late_after_minutes"?: number;
        };
        Relationships: [];
      };
    };
    Views: {
      "attendance_report_counts": {
        Row: {
          "group_id": string | null;
          "membership_id": string | null;
          "activity_type_id": string | null;
          "activity_date": string | null;
          "convened": number | null;
          "present": number | null;
          "late": number | null;
          "absent": number | null;
          "excused": number | null;
          "attendance_pct": number | null;
          "late_rate": number | null;
        };
        Insert: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_type_id"?: string | null;
          "activity_date"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Update: {
          "group_id"?: string | null;
          "membership_id"?: string | null;
          "activity_type_id"?: string | null;
          "activity_date"?: string | null;
          "convened"?: number | null;
          "present"?: number | null;
          "late"?: number | null;
          "absent"?: number | null;
          "excused"?: number | null;
          "attendance_pct"?: number | null;
          "late_rate"?: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      "accept_invitation": { Args: { "p_token_hash": string; "p_auth_user_id": string; "p_registration"?: Json }; Returns: Json };
      "account_terms_version": { Args: {  }; Returns: string };
      "activity_local_to_utc": { Args: { "p_local": string }; Returns: string };
      "actor_claims": { Args: {  }; Returns: Json };
      "actor_role": { Args: {  }; Returns: string };
      "actor_subject_id": { Args: {  }; Returns: string };
      "announcement_worker_metrics": { Args: {  }; Returns: Json };
      "api_accept_invitation": { Args: { "p_token_hash": string }; Returns: Json };
      "api_issue_invitation": { Args: { "p_group_id": string; "p_token_hash": string; "p_email"?: string; "p_role"?: string; "p_invitation_id"?: string; "p_membership_id"?: string }; Returns: Json };
      "attendance_metrics": { Args: { "p_present": number; "p_late": number; "p_absent": number; "p_excused": number }; Returns: { "convened": number; "present": number; "late": number; "absent": number; "excused": number; "attendance_pct": number; "late_rate": number }[] };
      "attendance_period_bounds": { Args: { "p_period": string; "p_from": string; "p_to": string; "p_created_at": string }; Returns: { "from_date": string; "until_date": string; "from_utc": string; "until_utc": string }[] };
      "auth_cutover": { Args: { "p_action": string }; Returns: Json };
      "auth_is_native": { Args: {  }; Returns: boolean };
      "auth_operation": { Args: { "p_operation": string; "p_data": Json }; Returns: Json };
      "begin_subscription_checkout": { Args: { "p_group_id": string; "p_actor_auth_id": string; "p_plan_code": string }; Returns: Json };
      "billing_actor": { Args: { "p_group_id": string; "p_auth_id": string }; Returns: string };
      "billing_canonical_begin_subscription_checkout": { Args: { "p_group_id": string; "p_actor_auth_id": string; "p_plan_code": string }; Returns: Json };
      "billing_canonical_claim_subscription_creation": { Args: { "p_subscription_id": string }; Returns: boolean };
      "billing_canonical_get_subscription_context": { Args: { "p_group_id": string; "p_actor_auth_id": string }; Returns: Json };
      "billing_canonical_lookup_billing_subscription": { Args: { "p_subscription_id": string }; Returns: Json };
      "billing_canonical_reject_subscription_creation": { Args: { "p_subscription_id": string }; Returns: undefined };
      "billing_canonical_sync_group_subscription": { Args: { "p_subscription_id": string; "p_provider_id": string; "p_status": string; "p_provider_updated_at": string; "p_next_payment_at": string; "p_checkout_url": string }; Returns: undefined };
      "billing_canonical_sync_subscription_invoice": { Args: { "p_provider_subscription_id": string; "p_invoice_id": string; "p_due_at": string; "p_amount_clp": number; "p_currency": string; "p_status": string; "p_payment_id": string; "p_paid_at": string; "p_provider_updated_at": string }; Returns: undefined };
      "billing_gate": { Args: { "p_mode": string }; Returns: undefined };
      "can_manage_attendance": { Args: { "p_group_id": string }; Returns: boolean };
      "can_read_group_activities": { Args: { "p_group_id": string }; Returns: boolean };
      "can_view_group_stats": { Args: { "p_group_id": string }; Returns: boolean };
      "canonical_claim_announcement_push": { Args: { "p_receipts"?: boolean }; Returns: { "delivery_id": string; "claim_token": string; "token": string; "announcement_id": string; "group_id": string; "ticket_id": string }[] };
      "canonical_complete_announcement_push": { Args: { "p_delivery_id": string; "p_claim_token": string; "p_outcome": string; "p_ticket_id"?: string }; Returns: undefined };
      "canonical_record_announcement_push_run": { Args: { "p_processed": number }; Returns: undefined };
      "change_membership_status": { Args: { "p_group_id": string; "p_membership_id": string; "p_active": boolean }; Returns: undefined };
      "chile_today": { Args: {  }; Returns: string };
      "claim_subscription_creation": { Args: { "p_subscription_id": string }; Returns: boolean };
      "create_single_activity": { Args: { "p_group_id": string; "p_activity_type_id": string; "p_title": string; "p_starts_at": string; "p_ends_at": string; "p_description"?: string; "p_location"?: string }; Returns: string };
      "get_subscription_context": { Args: { "p_group_id": string; "p_actor_auth_id": string }; Returns: Json };
      "group_athlete_limit": { Args: { "p_group_id": string }; Returns: number };
      "group_membership_limit": { Args: { "p_group_id": string }; Returns: number };
      "has_account_activation_consent": { Args: { "p_user_id": string }; Returns: boolean };
      "has_minor_consent": { Args: { "p_user_id": string; "p_avatar"?: boolean }; Returns: boolean };
      "identity_auth_operation": { Args: { "p_operation": string; "p_data": Json }; Returns: Json };
      "is_minor": { Args: { "p_birthdate": string }; Returns: boolean };
      "lock_activity_series": { Args: { "p_group_id": string; "p_activity_id": string }; Returns: string };
      "lock_attendance_activity": { Args: { "p_activity_id": string }; Returns: string };
      "lookup_billing_subscription": { Args: { "p_subscription_id": string }; Returns: Json };
      "majority_transition": { Args: {  }; Returns: number };
      "native_session_user_id": { Args: { "p_session_id": string }; Returns: string };
      "password_auth_operation": { Args: { "p_operation": string; "p_data": Json }; Returns: Json };
      "qr_checkin_status": { Args: { "p_starts_at": string; "p_now": string; "p_opens_before": number; "p_closes_after": number; "p_late_after": number }; Returns: string };
      "qr_checkin_token": { Args: { "p_activity_id": string; "p_secret": string; "p_now": string }; Returns: string };
      "record_account_consent": { Args: { "p_user_id": string; "p_terms_version": string; "p_channel": string }; Returns: string };
      "reject_subscription_creation": { Args: { "p_subscription_id": string }; Returns: undefined };
      "require_announcement_admin": { Args: { "p_group_id": string }; Returns: string };
      "review_pending_membership": { Args: { "p_group_id": string; "p_membership_id": string; "p_approve": boolean }; Returns: undefined };
      "sync_group_subscription": { Args: { "p_subscription_id": string; "p_provider_id": string; "p_status": string; "p_provider_updated_at": string; "p_next_payment_at": string; "p_checkout_url": string }; Returns: undefined };
      "sync_subscription_invoice": { Args: { "p_provider_subscription_id": string; "p_invoice_id": string; "p_due_at": string; "p_amount_clp": number; "p_currency": string; "p_status": string; "p_payment_id": string; "p_paid_at": string; "p_provider_updated_at": string }; Returns: undefined };
      "worker_claim_announcement_push": { Args: { "p_receipts"?: boolean }; Returns: { "delivery_id": string; "claim_token": string; "token": string; "announcement_id": string; "group_id": string; "ticket_id": string }[] };
      "worker_claim_email": { Args: {  }; Returns: { "delivery_id": string; "claim_token": string; "email": string; "full_name": string; "audience": string; "payload": Json }[] };
      "worker_claim_transition": { Args: {  }; Returns: { "run_date": string; "lease_token": string }[] };
      "worker_complete_announcement_push": { Args: { "p_delivery_id": string; "p_claim_token": string; "p_outcome": string; "p_ticket_id"?: string }; Returns: undefined };
      "worker_complete_transition": { Args: { "p_date": string; "p_token": string }; Returns: boolean };
      "worker_email_payload": { Args: { "p_id": string; "p_token": string; "p_payload": Json }; Returns: Json };
      "worker_finish_email": { Args: { "p_id": string; "p_token": string; "p_sent": boolean }; Returns: boolean };
      "worker_metrics": { Args: {  }; Returns: Json };
      "worker_now": { Args: {  }; Returns: string };
      "worker_record_announcement_push_run": { Args: { "p_processed": number }; Returns: undefined };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
