import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { check, suite, verify, evidence } from './run.mjs';
import { withEdge } from './edge.mjs';
await suite('backend', async () => {
  await check('supabase-local-start', 'pnpm', ['exec', 'supabase', 'start']);
  await check('database-migrations', 'pnpm', ['exec', 'supabase', 'migration', 'up', '--local']);
  await check('api-session-build', 'pnpm', ['exec', 'turbo', 'run', 'build', '--filter', '@asisteam/api']);
  await check('worker-build', 'pnpm', ['exec', 'turbo', 'run', 'build', '--filter', '@asisteam/worker']);
  await check('independent-postgres-api-worker-types-backup-pitr', 'node', ['apps/api/test/independent-postgres.integration.mjs']);
  await check('worker-two-replicas', 'pnpm', ['--filter', '@asisteam/worker', 'test:integration'], { env: { WORKER_TEST: '1' }, noSkip: true });
  await check('private-storage-fixture-build', 'docker', ['build', '-f', 'scripts/migration/storage/Dockerfile.fixture', '-t', 'asisteam-storage-fixture:161', '.']);
  await check('api-private-storage-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/storage.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('next-native-auth-browser', 'pnpm', ['--filter', '@asisteam/web', 'test:auth-contract']);
  await check('next-social-auth-browser', 'pnpm', ['--filter', '@asisteam/web', 'test:social-contract']);
  await check('api-social-auth-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/social-auth.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-native-auth-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/native-auth.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-auth-cutover-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/auth-cutover.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-session-rls-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/session-rls.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-groups-profile-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/groups-profile.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-members-consents-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/members-consents.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-activities-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/activities.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-announcements-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/announcements.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-billing-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/billing.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-reports-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/reports.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-qr-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/qr.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-attendance-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/attendance.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('api-invitations-http', 'pnpm', ['--filter', '@asisteam/api', 'exec', 'node', '--test', '--test-reporter=tap', 'test/invitations.integration.mjs'], { env: { API_RLS_TEST: '1' }, noSkip: true });
  await check('portability-rehearsal', 'pnpm', ['migration:portability']);
  verify('portability-no-omissions', () => {
    const report = JSON.parse(readFileSync('.ci-results/portability.json', 'utf8'));
    assert.ok(report.checks.length >= 15 && report.checks.every(record => record.status === 'PASS'));
  });
  const faultStart = evidence.checks.length;
  await assert.rejects(check('portability-injected-failure', 'pnpm', ['migration:portability'], { env: { PORTABILITY_FAIL_AFTER: 'local-storage-export' } }));
  for (const record of evidence.checks.slice(faultStart)) if (record.status === 'FAIL') record.expected = true;
  verify('portability-cleanup-after-failure', () => {
    const report = JSON.parse(readFileSync('.ci-results/portability-fault.json', 'utf8'));
    assert.equal(report.checks.filter(record => record.status === 'FAIL').length, 1);
    assert.equal(report.checks.find(record => record.check === 'local-storage-export').status, 'FAIL');
    assert.equal(report.checks.find(record => record.check === 'owned-resource-cleanup').status, 'PASS');
  });
  const generated = await check('database-types-generation', 'pnpm', ['exec', 'supabase', 'gen', 'types', 'typescript', '--local']);
  verify('database-types-match', () => assert.equal(generated.trim(), readFileSync('packages/db/src/database.types.ts', 'utf8').trim()));
  await check('pgtap-all', 'pnpm', ['exec', 'supabase', 'test', 'db']);
  await withEdge(secret => check('product-integrations', 'pnpm', ['--filter', '@asisteam/web', 'test:integration:modules', '--reporter=json', '--outputFile=.ci-integration.json'], { env: { INVITATION_PROXY_SECRET: secret }, report: 'apps/web/.ci-integration.json', requireAll: true }));
});
