begin;
\i packages/db/fixtures/domain.sql

select no_plan();
select is((select mode from app_private.announcement_executor),'WORKER','instalación usa worker independiente');
select ok((select relrowsecurity from pg_class where oid='app_private.announcement_executor'::regclass),'executor is deny-by-default RLS');
update app_private.announcement_executor set mode='DRAINING';
select is((select count(*) from app_private.worker_claim_announcement_push(false)),0::bigint,'worker cannot claim before handoff');
select ok(not has_table_privilege('asisteam_jobs','public.push_tokens','SELECT'),'jobs has no token table access');
select ok(not has_table_privilege('asisteam_jobs','app_private.announcement_push_deliveries','SELECT,UPDATE'),'jobs cannot read or forge queue');
select ok(not has_column_privilege('asisteam_api','public.push_tokens','token','SELECT'),'API never reads token column');
select ok(has_column_privilege('asisteam_api','public.push_tokens','id','SELECT'),'API may project device existence under RLS');
select ok(pg_temp.can_execute('asisteam_api','public.publish_group_announcement(uuid,text,text,uuid)','EXECUTE'),'API uses canonical write');
select ok(not pg_temp.can_execute('asisteam_api','app_private.worker_claim_announcement_push(boolean)','EXECUTE'),'API cannot claim deliveries');
select ok(not pg_temp.can_execute('asisteam_test_operator','app_private.worker_claim_announcement_push(boolean)','EXECUTE'),'legacy credential cannot use worker');
select ok(not pg_temp.can_execute('asisteam_jobs','public.claim_announcement_push(boolean)','EXECUTE'),'worker cannot use legacy claim');
select ok(not pg_temp.can_execute('asisteam_jobs','app_private.canonical_claim_announcement_push(boolean)','EXECUTE'),'worker cannot bypass executor mode');
select ok(not pg_temp.can_execute('asisteam_test_operator','app_private.canonical_complete_announcement_push(uuid,uuid,text,text)','EXECUTE'),'legacy cannot bypass receipt fence');
select ok(not pg_temp.can_execute('asisteam_jobs','app_private.announcement_handoff(text,boolean)','EXECUTE'),'jobs cannot activate handoff');
select ok(not pg_temp.can_execute('asisteam_api','app_private.announcement_handoff(text,boolean)','EXECUTE'),'API cannot activate handoff');
select ok(not pg_temp.can_execute('asisteam_member','app_private.announcement_handoff(text,boolean)','EXECUTE'),'user cannot activate handoff');
select ok((select bool_and(prosecdef and proconfig @> array['search_path=""']) from pg_proc where oid in ('app_private.worker_claim_announcement_push(boolean)'::regprocedure,'app_private.worker_complete_announcement_push(uuid,uuid,text,text)'::regprocedure)),'privileged functions have fixed search_path');
update app_private.announcement_executor set mode='DRAINING',draining_since=now();
select is((select count(*) from pg_namespace where nspname='cron'),0::bigint,'no scheduler proveedor activo');
select ok(to_regprocedure('public.claim_announcement_push(boolean)') is null,'legacy claims fenced while draining (capacidad retirada)');
select ok(to_regprocedure('app_private.dispatch_announcement_push()') is null,'dispatcher proveedor retirado');
select ok(not pg_temp.can_execute('asisteam_jobs','app_private.announcement_handoff(text,boolean)','EXECUTE'),'worker no puede autoactivar transporte');
update app_private.announcement_executor set draining_since=now()-interval '4 minutes';
select is((select mode from app_private.announcement_executor),'DRAINING','paso del tiempo no activa ejecutor');
update app_private.announcement_executor set mode='WORKER',activated_at=now();
select is((select mode from app_private.announcement_executor),'WORKER','operator activation recorded');
select ok((select activated_at is not null and draining_since is not null from app_private.announcement_executor),'handoff keeps timestamps for evidence');
select ok(to_regprocedure('public.claim_announcement_push(boolean)') is null,'legacy claims remain disabled (capacidad retirada)');
select ok(to_regprocedure('public.complete_announcement_push(uuid,uuid,text,text)') is null,'legacy ACK cannot write after activation (capacidad retirada)');
select throws_ok($$select app_private.worker_complete_announcement_push(gen_random_uuid(),gen_random_uuid(),'accepted','ticket')$$,'55000','Reserva vencida o cancelada','unleased worker ACK fenced');
select ok(to_regprocedure('app_private.announcement_handoff(text,boolean)') is null,'no transición a proveedor en catálogo');
select ok(not (app_private.announcement_worker_metrics()::text ~ 'token|user_id|title|body'),'metrics contain only aggregates');
select * from finish();
rollback;
