import assert from 'node:assert/strict';
import { test } from 'node:test';
import { ApiClient } from '../dist/index.js';
const groupId='17000000-0000-4000-8000-000000000201',activityId='17000000-0000-4000-8000-000000000202';
const body={title:'Actividad sintética',activity_type_id:activityId,description:'',location:'',starts_at:'2026-09-05T22:30:00Z',ends_at:'2026-09-06T00:00:00Z'};
const response={id:activityId,group_id:groupId,activity_type_id:activityId,title:body.title,description:null,location:null,starts_at:body.starts_at,ends_at:body.ends_at,activity_type_name:'TRAINING',activity_type_color:'#123456',is_system_type:true,recurrence_rule:null,recurrence_source_id:null};
function client(payload,status=200){const requests=[];return {requests,api:new ApiClient({origin:'http://127.0.0.1:4000',accessToken:async()=>'synthetic',fetch:async(url,options)=>{requests.push({url:String(url),...options});return new Response(JSON.stringify(payload),{status});}})};}
test('activities SDK uses typed group/global paths, pagination and stable DTO',async()=>{const {api,requests}=client({activities:[response],hasNext:false});await api.listGroupActivities({params:{groupId},query:{page:2,period:'past'}});assert.equal(new URL(requests[0].url).pathname,'/api/v1/groups/'+groupId+'/activities');assert.equal(new URL(requests[0].url).searchParams.get('page'),'2');await api.listActivities({query:{group_ids:groupId}});assert.equal(new URL(requests[1].url).pathname,'/api/v1/me/activities');assert.equal(requests[0].cache,'no-store');});
test('activities SDK preserves UTC body and series/single scope',async()=>{const {api,requests}=client({activityId},201);assert.deepEqual(await api.createActivity({params:{groupId},body}),{activityId});assert.deepEqual(JSON.parse(requests[0].body),body);const mutation=client({affected:2});await mutation.api.updateActivity({params:{groupId,activityId},body:{...body,scope:'series'}});assert.equal(mutation.requests[0].method,'PATCH');await mutation.api.deleteActivity({params:{groupId,activityId},body:{scope:'single',confirm_attendance:false}});assert.equal(mutation.requests[1].method,'DELETE');});
test('activities rejects actor/scope/date/recurrence and unknown filters before network',async()=>{const {api,requests}=client({activityId},201);for(const invalid of [{...body,actor:groupId},{...body,starts_at:'2026-09-05T18:30'},{...body,ends_at:body.starts_at},{...body,recurrence_rule:{freq:'WEEKLY',by_weekday:['MO'],until:'2099-01-01'}}])await assert.rejects(api.createActivity({params:{groupId},body:invalid}),{status:400});await assert.rejects(api.listActivities({query:{group_ids:groupId,actor:activityId}}),{status:400});assert.equal(requests.length,0);});
test('activities third-party response is strict: PII fields reject payload',async()=>{const {api}=client({...response,email:'synthetic@example.test'});await assert.rejects(api.getActivity({params:{groupId,activityId}}),{status:502});});
test('types transport keeps page100 and inactive selector',async()=>{const {api,requests}=client({data:[],hasNext:false});await api.listActivityTypes({params:{groupId},query:{page:3,include_inactive:true}});assert.equal(new URL(requests[0].url).searchParams.get('include_inactive'),'true');const save=client({id:activityId});await save.api.updateActivityType({params:{groupId,typeId:activityId},body:{name:'Tipo',color:'#123456',is_active:false}});assert.equal(save.requests[0].method,'PATCH');});
