BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path=public,extensions;
SELECT plan(23);
SELECT is((select count(*)::integer from pg_namespace where nspname in ('auth','storage','net','cron','vault')),0,'no provider schemas');
SELECT is((select count(*)::integer from pg_roles where rolname in ('anon','authenticated','service_role','supabase_admin','supabase_auth_admin','supabase_storage_admin')),0,'no provider roles');
SELECT is((select count(*)::integer from pg_extension where extname in ('pg_net','pg_cron','supabase_vault')),0,'no provider extensions');
SELECT is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','app_private') and p.prosrc ~ '\m(auth|storage|net|cron|vault)\.'),0,'no function provider references');
SELECT is((select count(*)::integer from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','app_private') and p.prosecdef and not coalesce('search_path=""'=any(p.proconfig),false)),0,'fixed definer search paths');
SELECT is((select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app_private') and c.relowner<>'asisteam_migrator'::regrole),0,'deploy role owns objects');
SELECT is((select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app_private') and c.relkind='r' and not c.relrowsecurity),0,'all business tables have RLS');
SELECT ok(not pg_has_role('asisteam_api','asisteam_migrator','MEMBER'),'API cannot become owner');
SELECT ok(not has_schema_privilege('asisteam_api','public','CREATE'),'API cannot create');
SELECT ok(not has_schema_privilege('asisteam_jobs','app_private','CREATE'),'worker cannot create');
SELECT ok(not has_table_privilege('asisteam_jobs','public.users','SELECT'),'worker cannot read profiles');
SELECT ok(not has_table_privilege('asisteam_auth','app_private.auth_credentials','SELECT'),'Auth cannot read hash table');
SELECT ok(not has_table_privilege('asisteam_invitation','public.invitations','SELECT'),'invitation cannot read table');
SELECT ok(not has_table_privilege('asisteam_billing','public.subscription_invoices','UPDATE'),'billing cannot write ledger directly');
SELECT ok(not has_function_privilege('asisteam_api','app_private.auth_cutover(text)','EXECUTE'),'API cannot switch authority');
SELECT ok(not has_function_privilege('asisteam_jobs','app_private.auth_operation(text,jsonb)','EXECUTE'),'worker cannot issue sessions');
SELECT ok(has_function_privilege('asisteam_auth','app_private.auth_operation(text,jsonb)','EXECUTE'),'Auth minimal RPC');
SELECT ok(has_function_privilege('asisteam_jobs','app_private.worker_claim_transition()','EXECUTE'),'worker minimal RPC');
SELECT is((select mode from app_private.auth_authority),'NATIVE','native authority');
SELECT is((select mode from app_private.majority_executor),'WORKER','one majority executor');
SELECT is((select mode from app_private.announcement_executor),'WORKER','one push executor');
SELECT is((select count(*)::integer from public.activity_types where group_id is null),4,'four immutable system types');
SELECT ok(to_regclass('app_private.auth_import_ledger') is not null and to_regclass('public.consents') is not null and to_regclass('public.subscription_invoices') is not null,'history and evidence retained');
SELECT * FROM finish();
ROLLBACK;
