-- Cluster administrator runs once. Credentials are assigned privately by the
-- secret manager; runtime roles have NOLOGIN until that separate operation.
CREATE ROLE asisteam_migrator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE asisteam_member NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE asisteam_api NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;
CREATE ROLE asisteam_jobs NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;
CREATE ROLE asisteam_auth NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;
CREATE ROLE asisteam_invitation NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;
CREATE ROLE asisteam_billing NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT;
GRANT asisteam_member TO asisteam_api WITH INHERIT TRUE, SET FALSE;
CREATE SCHEMA extensions AUTHORIZATION asisteam_migrator;
CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO asisteam_migrator;
DO $$ BEGIN
 EXECUTE format('REVOKE ALL ON DATABASE %I FROM PUBLIC',current_database());
 EXECUTE format('GRANT CREATE,TEMPORARY ON DATABASE %I TO asisteam_migrator',current_database());
 EXECUTE format('GRANT CONNECT ON DATABASE %I TO asisteam_migrator,asisteam_api,asisteam_jobs,asisteam_auth,asisteam_invitation,asisteam_billing',current_database());
END $$;
