// Persistence types come from PostgreSQL catalogs, independently of HTTP DTOs
// and the archived Supabase generator. No data rows are read.
import pg from 'pg';
import {readFile,writeFile} from 'node:fs/promises';
const scalars={bool:'boolean',int2:'number',int4:'number',int8:'number',float4:'number',float8:'number',numeric:'number',json:'Json',jsonb:'Json',void:'undefined'};
const type=name=>name.startsWith('_')?'('+type(name.slice(1))+')[]':scalars[name]??'string';
const key=value=>JSON.stringify(value);
export async function persistenceTypes(client) {
 const columns=(await client.query(`select n.nspname as schema,c.relname,c.relkind,a.attname,t.typname,a.attnotnull,
  (a.atthasdef or a.attidentity<>'' or a.attgenerated<>'') as optional
  from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid join pg_type t on t.oid=a.atttypid
  where n.nspname in ('public','app_private') and c.relkind in ('r','p','v','m') and a.attnum>0 and not a.attisdropped order by n.nspname,c.relname,a.attnum`)).rows;
 const funcs=(await client.query(`select n.nspname as schema,p.proname,p.proretset,t.typname as result,p.pronargdefaults,
  coalesce(p.proargnames,'{}') as names,coalesce(p.proargmodes,array_fill('i'::"char",array[p.pronargs]))::text[] as modes,
  array(select typname::text from unnest(coalesce(p.proallargtypes,p.proargtypes::oid[])) with ordinality x(id,i) join pg_type t on t.oid=x.id order by i) as types
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_type t on t.oid=p.prorettype where n.nspname in ('public','app_private') and p.prokind='f' and t.typname<>'trigger' order by n.nspname,p.proname,p.oid::regprocedure::text`)).rows;
 let output='// Generated by packages/db/scripts/types.mjs from PostgreSQL 17 catalogs.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type PersistenceSchema = {\n';
 for(const schema of ['public','app_private']) {
  output+='  '+key(schema)+': {\n';
  for(const [category,kinds] of [['Tables',['r','p']],['Views',['v','m']]]) {
   output+='    '+category+': {\n';
   for(const name of [...new Set(columns.filter(c=>c.schema===schema&&kinds.includes(c.relkind)).map(c=>c.relname))]){
    const fields=columns.filter(c=>c.schema===schema&&c.relname===name);
    output+='      '+key(name)+': {\n';
    for(const mode of ['Row','Insert','Update']){
     output+='        '+mode+': {\n';
     for(const c of fields)output+='          '+key(c.attname)+(mode==='Update'||mode==='Insert'&&(c.optional||!c.attnotnull)?'?':'')+': '+type(c.typname)+(!c.attnotnull?' | null':'')+';\n';
     output+='        };\n';
    }
    output+='        Relationships: [];\n      };\n';
   }
   output+='    };\n';
  }
  output+='    Functions: {\n';
  for(const name of [...new Set(funcs.filter(f=>f.schema===schema).map(f=>f.proname))]){
   const overloads=funcs.filter(f=>f.schema===schema&&f.proname===name);
   const definitions=overloads.map(f=>{
    const input=f.types.flatMap((t,i)=>['i','b','v'].includes(f.modes[i])?[i]:[]),out=f.types.flatMap((t,i)=>['o','b','t'].includes(f.modes[i])?[i]:[]);
    const args=input.map((i,n)=>key(f.names[i]??('arg'+n))+(n>=input.length-f.pronargdefaults?'?':'')+': '+type(f.types[i])).join('; ');
    let result=out.length?'{ '+out.map(i=>key(f.names[i])+': '+type(f.types[i])).join('; ')+' }':type(f.result);
    const composite=columns.filter(c=>c.schema===schema&&c.relname===f.result);
    if(composite.length&&!out.length)result='PersistenceSchema['+key(schema)+']["Tables"]['+key(f.result)+']["Row"]';
    return '{ Args: { '+args+' }; Returns: '+result+(f.proretset?'[]':'')+' }';
   });
   output+='      '+key(name)+': '+definitions.join(' | ')+';\n';
  }
  output+='    };\n    Enums: Record<never, never>;\n    CompositeTypes: Record<never, never>;\n  };\n';
 }
 return output+'};\n';
}
if(process.argv[1]===new URL(import.meta.url).pathname){
 const client=new pg.Client({connectionString:process.env.DB_TYPES_URL}),path=new URL('../src/persistence.types.ts',import.meta.url);
 try{if(!process.env.DB_TYPES_URL)throw new Error('types_connection_required');await client.connect();const output=await persistenceTypes(client);if(process.argv.includes('--check')){if(output!==await readFile(path,'utf8'))throw new Error('persistence_types_diverged');}else await writeFile(path,output);console.log('persistence_types PASS');}
 catch{console.error('persistence_types FAIL');process.exitCode=1;}finally{await client.end();}
}
