import {beforeEach,describe,expect,it,vi} from 'vitest';
import {MajorityWorker,majorityText} from '../../../worker/dist/worker.js';
import {SafeLogger} from '../../../api/dist/logger.js';
const deliveries=['ATHLETE','GUARDIAN','ADMIN'].map((audience,index)=>({delivery_id:`delivery-${index}`,claim_token:`lease-${index}`,email:`synthetic-${index}@example.test`,full_name:'Deportista sintético',audience}));
const call=vi.fn(),send=vi.fn(),logs:string[]=[];
const email={payload:(to:string,subject:string,text:string)=>({from:'fixture',to:[to],subject,text}),send};
const worker=()=>new MajorityWorker({call},email,new SafeLogger((line:string)=>logs.push(line)));
beforeEach(()=>{vi.resetAllMocks();logs.length=0;call.mockImplementation(async(operation,values)=>operation==='transition'?[{run_date:'2026-10-09',lease_token:'lease'}]:operation==='email'?[deliveries[0]]:operation==='payload'?[{payload:JSON.parse(values[2])}]:operation==='metrics'?[{metrics:{pending:0,blocked:0,retries:0,oldest_seconds:0,transition_overdue:false}}]:[]);send.mockResolvedValue(undefined);});
describe('worker nativo de mayoría de edad',()=>{
 it('capacidad SQL inválida no consulta correo ni registra PII',async()=>{call.mockRejectedValue(new Error('denied-private'));await worker().tick();expect(call).toHaveBeenCalledOnce();expect(send).not.toHaveBeenCalled();expect(logs.join()).not.toContain('private');expect(logs.join()).toContain('worker_failed');});
 it('persiste transición y avisa a las tres audiencias con payload durable',async()=>{for(const delivery of deliveries){call.mockImplementation(async(op,values)=>op==='transition'?[{run_date:'2026-10-09',lease_token:'lease'}]:op==='email'?[delivery]:op==='payload'?[{payload:JSON.parse(values[2])}]:[]);await worker().tick();const [payload,key]=send.mock.calls.at(-1)!;expect(payload.to).toEqual([delivery.email]);expect(payload.text).toContain('18 años');expect(payload.html).toBeUndefined();expect(key).toBe('guardianship-majority-'+delivery.delivery_id);expect(call).toHaveBeenCalledWith('finish',[delivery.delivery_id,delivery.claim_token,true]);}expect(send).toHaveBeenCalledTimes(3);expect(call.mock.calls[0]![0]).toBe('transition');expect(call.mock.calls[1]![0]).toBe('complete');expect(logs.join()).not.toContain('synthetic-');});
 it('falta de correo no impide transición ni confirma entrega',async()=>{send.mockRejectedValue(new Error('not configured'));await worker().tick();expect(call.mock.calls[1]![0]).toBe('complete');expect(call).toHaveBeenCalledWith('finish',['delivery-0','lease-0',false]);expect(logs.join()).not.toContain('configured');});
 it('fallo del proveedor mantiene reintento y oculta detalles',async()=>{send.mockRejectedValue(new Error('secret@example.test'));await worker().tick();expect(call).toHaveBeenCalledWith('finish',['delivery-0','lease-0',false]);expect(logs.join()).not.toContain('secret');expect(send).toHaveBeenCalledOnce();});
 it('reintento utiliza misma clave y payload persistido antes de ACK',async()=>{const payload=email.payload('original@example.test','Fixed','Fixed');call.mockImplementation(async(op,values)=>op==='email'?[{...deliveries[0],payload}]:op==='payload'?[{payload}]:op==='finish'?Promise.reject(new Error('private ACK')):[]);await worker().tick();await worker().tick();expect(send.mock.calls[0]).toEqual(send.mock.calls[1]);expect(send.mock.calls[0]![1]).toBe('guardianship-majority-delivery-0');expect(call).toHaveBeenCalledWith('payload',['delivery-0','lease-0',JSON.stringify(payload)]);expect(logs.join()).not.toContain('private');});
 it('lease expirado o respuesta DB inválida no envía',async()=>{call.mockImplementation(async(op)=>op==='email'?[deliveries[0]]:[]);await worker().tick();expect(send).not.toHaveBeenCalled();expect(call).toHaveBeenCalledWith('finish',['delivery-0','lease-0',false]);expect(majorityText('ATHLETE','Fixture')).toContain('cuenta aún es gestionada');});
 it('cola completada no vuelve a enviar',async()=>{call.mockResolvedValue([]);await worker().tick();expect(send).not.toHaveBeenCalled();expect(call.mock.calls.map(([op])=>op)).toEqual(['transition','email','metrics']);expect(logs).toEqual([]);});
});
